#!/bin/bash
# Script used to build and run a target from the current directory
# Usage: ./build-run <target> [args...]

build() {
	cmake -S . -B .build 1>/dev/null 2>/tmp/cmake_err.log || {
		echo "Failed to configure project"
		cat /tmp/cmake_err.log
		return 1
	}
	cmake --build .build -t "$1" 1>/dev/null 2>/tmp/cmake_err.log || {
		echo "Failed to build target"
		cat /tmp/cmake_err.log
		return 1
	}
	return 0
}

[ -z "$1" ] && echo "Usage: $0 <target> [args...]" && exit 1
build "$1" || exit 1
./"$1" ${@:1}
