#   You have full freedom of the code in this file.
#   You may adapt the current build framework to your needs, or write your own from scratch.
#   If you want to add this file to the current build system, you need to modify
#         .cmake/executables.cmake
#   However, we recommend you to write your own build system from scratch, using Makefile or CMake, or even a shell script.
#   You must document how to run your code in the how-to-run.md file and submit it with your code.
#   Good luck!